-- CityLand 9 Condo Management System: local MySQL 8 / MariaDB 10.4+ schema
-- GENERATED by database/tools/generate_schema.py from backend/legacy_app.py.
-- Do not edit by hand; change the models and regenerate.
--
-- Apply ONLY to a new, empty database, for example:
--   CREATE DATABASE cityland9 CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
--   mysql -u <user> -p cityland9 < database/schema.sql
--
-- Tables: 35 (ordered so foreign-key targets are created first)

SET NAMES utf8mb4;

-- announcement
CREATE TABLE announcement (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	title VARCHAR(200) NOT NULL, 
	message TEXT NOT NULL, 
	audience VARCHAR(30), 
	published BOOL, 
	publish_date DATE, 
	created_by VARCHAR(80), 
	created_at DATETIME(6), 
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- audit_log
CREATE TABLE audit_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	username VARCHAR(80), 
	action VARCHAR(255), 
	created_at DATETIME(6), 
	entity_type VARCHAR(40), 
	entity_id INTEGER, 
	reason VARCHAR(500), 
	details TEXT, 
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_audit_log_entity ON audit_log (entity_type, entity_id);

-- employee
CREATE TABLE employee (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	employee_no VARCHAR(50) NOT NULL, 
	full_name VARCHAR(200) NOT NULL, 
	position VARCHAR(120), 
	department VARCHAR(120), 
	employment_status VARCHAR(40), 
	contact_no VARCHAR(80), 
	email VARCHAR(160), 
	date_hired DATE, 
	monthly_salary NUMERIC(12, 2), 
	notes VARCHAR(500), 
	created_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	UNIQUE (employee_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- employee_hr_setting
CREATE TABLE employee_hr_setting (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	`key` VARCHAR(80) NOT NULL, 
	value VARCHAR(255), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	UNIQUE (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- expense
CREATE TABLE expense (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	expense_date DATE, 
	category VARCHAR(100), 
	description VARCHAR(300), 
	amount NUMERIC(12, 2), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- form_submission
CREATE TABLE form_submission (
	token VARCHAR(64) NOT NULL, 
	action VARCHAR(60) NOT NULL, 
	user_id INTEGER, 
	created_at DATETIME(6), 
	PRIMARY KEY (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- import_source
CREATE TABLE import_source (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	code VARCHAR(40) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	description VARCHAR(500), 
	created_at DATETIME(6), 
	created_by VARCHAR(80), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_import_source_code UNIQUE (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- receipt_counter
CREATE TABLE receipt_counter (
	year INTEGER NOT NULL, 
	last_seq INTEGER NOT NULL, 
	PRIMARY KEY (year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- setting
CREATE TABLE setting (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	`key` VARCHAR(80), 
	value VARCHAR(255), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	UNIQUE (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- unit
CREATE TABLE unit (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	unit_no VARCHAR(40) NOT NULL, 
	floor VARCHAR(20), 
	unit_type VARCHAR(50), 
	area_sqm DOUBLE, 
	unit_rate_per_sqm DOUBLE, 
	include_parking BOOL, 
	include_storage BOOL, 
	assigned_parking_unit_id INTEGER, 
	assigned_storage_unit_id INTEGER, 
	auto_rate BOOL, 
	dues_mode VARCHAR(20), 
	manual_monthly_dues NUMERIC(12, 2), 
	occupancy_type VARCHAR(20), 
	status VARCHAR(30), 
	active BOOL, 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	UNIQUE (unit_no), 
	FOREIGN KEY(assigned_parking_unit_id) REFERENCES unit (id), 
	FOREIGN KEY(assigned_storage_unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- user
CREATE TABLE user (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	username VARCHAR(80) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	`role` ENUM('super_admin','admin','manager','staff','accounting','resident'), 
	active BOOL, 
	created_at DATETIME(6), 
	session_version INTEGER NOT NULL DEFAULT '0', 
	must_change_password BOOL NOT NULL DEFAULT '0', 
	password_changed_at DATETIME(6), 
	temp_password_expires_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	UNIQUE (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- vendor
CREATE TABLE vendor (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	vendor_name VARCHAR(200) NOT NULL, 
	service_type VARCHAR(120), 
	contact_person VARCHAR(160), 
	contact_no VARCHAR(80), 
	email VARCHAR(160), 
	address VARCHAR(300), 
	status VARCHAR(30), 
	notes TEXT, 
	created_at DATETIME(6), 
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- advance_payment
CREATE TABLE advance_payment (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	unit_id INTEGER NOT NULL, 
	payment_date DATE, 
	amount NUMERIC(12, 2), 
	start_month VARCHAR(7) NOT NULL, 
	coverage_months INTEGER, 
	monthly_amount NUMERIC(12, 2), 
	payment_method VARCHAR(20), 
	reference VARCHAR(100), 
	remarks VARCHAR(300), 
	reversed_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	CONSTRAINT ck_advance_payment_month_format CHECK (start_month LIKE '____-__' AND SUBSTR(start_month, 1, 4) BETWEEN '1900' AND '2999' AND SUBSTR(start_month, 6, 2) BETWEEN '01' AND '12'), 
	CONSTRAINT ck_advance_payment_amount_nonneg CHECK (amount >= 0), 
	CONSTRAINT ck_advance_payment_coverage_min CHECK (coverage_months >= 1), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- billing
CREATE TABLE billing (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	unit_id INTEGER NOT NULL, 
	billing_month VARCHAR(7) NOT NULL, 
	assessment NUMERIC(12, 2), 
	parking_dues NUMERIC(12, 2), 
	storage_dues NUMERIC(12, 2), 
	water NUMERIC(12, 2), 
	other NUMERIC(12, 2), 
	penalty NUMERIC(12, 2), 
	adjustment NUMERIC(12, 2), 
	previous_balance NUMERIC(12, 2), 
	amount_paid NUMERIC(12, 2), 
	due_date DATE, 
	status VARCHAR(30), 
	paid_date DATE, 
	soa_note VARCHAR(1000), 
	soa_manual_override BOOL, 
	created_at DATETIME(6), 
	issued_at DATETIME(6), 
	issued_amount NUMERIC(12, 2), 
	penalty_rate NUMERIC(7, 4), 
	penalty_basis VARCHAR(60), 
	storage_included BOOL, 
	dues_basis VARCHAR(10), 
	condo_area NUMERIC(10, 2), 
	condo_rate NUMERIC(12, 4), 
	parking_unit_no VARCHAR(50), 
	parking_area NUMERIC(10, 2), 
	parking_rate NUMERIC(12, 4), 
	storage_unit_no VARCHAR(50), 
	storage_basis VARCHAR(10), 
	storage_area NUMERIC(10, 2), 
	storage_rate NUMERIC(12, 4), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_billing_unit_month UNIQUE (unit_id, billing_month), 
	CONSTRAINT ck_billing_month_format CHECK (billing_month LIKE '____-__' AND SUBSTR(billing_month, 1, 4) BETWEEN '1900' AND '2999' AND SUBSTR(billing_month, 6, 2) BETWEEN '01' AND '12'), 
	CONSTRAINT ck_billing_amount_paid_nonneg CHECK (amount_paid >= 0), 
	CONSTRAINT ck_billing_previous_balance_nonneg CHECK (previous_balance >= 0), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_billing_month ON billing (billing_month);
CREATE INDEX ix_billing_unit_month ON billing (unit_id, billing_month);

-- document_record
CREATE TABLE document_record (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	title VARCHAR(200) NOT NULL, 
	category VARCHAR(100), 
	description TEXT, 
	file_name VARCHAR(300), 
	file_path VARCHAR(500), 
	audience VARCHAR(30), 
	unit_id INTEGER, 
	active BOOL, 
	uploaded_by VARCHAR(80), 
	created_at DATETIME(6), 
	PRIMARY KEY (id), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- employee_attendance
CREATE TABLE employee_attendance (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	employee_id INTEGER NOT NULL, 
	attendance_date DATE NOT NULL, 
	time_in TIME, 
	time_out TIME, 
	status VARCHAR(30) NOT NULL, 
	remarks VARCHAR(255), 
	created_at DATETIME(6), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_employee_attendance_day UNIQUE (employee_id, attendance_date), 
	FOREIGN KEY(employee_id) REFERENCES employee (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_employee_attendance_attendance_date ON employee_attendance (attendance_date);
CREATE INDEX ix_employee_attendance_employee_id ON employee_attendance (employee_id);

-- employee_hr_loan
CREATE TABLE employee_hr_loan (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	employee_id INTEGER NOT NULL, 
	loan_type VARCHAR(60) NOT NULL, 
	reference_no VARCHAR(80), 
	original_amount NUMERIC(12, 2), 
	balance NUMERIC(12, 2), 
	monthly_deduction NUMERIC(12, 2), 
	status VARCHAR(20), 
	notes VARCHAR(300), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employee (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_employee_hr_loan_employee_id ON employee_hr_loan (employee_id);

-- employee_leave
CREATE TABLE employee_leave (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	employee_id INTEGER NOT NULL, 
	leave_type VARCHAR(50) NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE NOT NULL, 
	days NUMERIC(8, 2), 
	status VARCHAR(20), 
	reason VARCHAR(500), 
	approved_by VARCHAR(100), 
	created_at DATETIME(6), 
	PRIMARY KEY (id), 
	CONSTRAINT ck_employee_leave_dates CHECK (end_date >= start_date), 
	FOREIGN KEY(employee_id) REFERENCES employee (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_employee_leave_employee_id ON employee_leave (employee_id);

-- employee_overtime
CREATE TABLE employee_overtime (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	employee_id INTEGER NOT NULL, 
	ot_date DATE NOT NULL, 
	hours NUMERIC(8, 2), 
	rate_multiplier NUMERIC(8, 3), 
	amount NUMERIC(12, 2), 
	status VARCHAR(20), 
	reason VARCHAR(500), 
	approved_by VARCHAR(100), 
	created_at DATETIME(6), 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employee (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_employee_overtime_employee_id ON employee_overtime (employee_id);
CREATE INDEX ix_employee_overtime_ot_date ON employee_overtime (ot_date);

-- employee_payroll
CREATE TABLE employee_payroll (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	employee_id INTEGER NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	basic_salary NUMERIC(12, 2) NOT NULL, 
	overtime_pay NUMERIC(12, 2) NOT NULL, 
	allowances NUMERIC(12, 2) NOT NULL, 
	deductions NUMERIC(12, 2) NOT NULL, 
	absences NUMERIC(12, 2) NOT NULL, 
	late_undertime NUMERIC(12, 2) NOT NULL, 
	net_pay NUMERIC(12, 2) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remarks VARCHAR(255), 
	created_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employee (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_employee_payroll_employee_id ON employee_payroll (employee_id);
CREATE INDEX ix_employee_payroll_period_end ON employee_payroll (period_end);
CREATE INDEX ix_employee_payroll_period_start ON employee_payroll (period_start);

-- gate_pass
CREATE TABLE gate_pass (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	pass_date DATE, 
	unit_no VARCHAR(40), 
	visitor_name VARCHAR(200), 
	purpose VARCHAR(300), 
	status VARCHAR(30), 
	pass_type VARCHAR(20), 
	unit_id INTEGER, 
	requested_by VARCHAR(80), 
	requested_at DATETIME(6), 
	reviewed_by VARCHAR(80), 
	reviewed_at DATETIME(6), 
	review_note VARCHAR(300), 
	PRIMARY KEY (id), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_gate_pass_unit_id ON gate_pass (unit_id);

-- import_batch
CREATE TABLE import_batch (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	source_id INTEGER NOT NULL, 
	file_name VARCHAR(255) NOT NULL, 
	file_sha256 VARCHAR(64) NOT NULL, 
	sheet_summary TEXT, 
	status VARCHAR(20) NOT NULL DEFAULT 'started', 
	started_at DATETIME(6), 
	finished_at DATETIME(6), 
	created_by VARCHAR(80), 
	PRIMARY KEY (id), 
	FOREIGN KEY(source_id) REFERENCES import_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_import_batch_source ON import_batch (source_id);

-- move_certificate
CREATE TABLE move_certificate (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	certificate_no VARCHAR(50) NOT NULL, 
	move_type VARCHAR(20) NOT NULL, 
	person_type VARCHAR(20) NOT NULL, 
	unit_id INTEGER NOT NULL, 
	person_id INTEGER NOT NULL, 
	person_name VARCHAR(200) NOT NULL, 
	move_date DATE, 
	certificate_date DATE NOT NULL, 
	issued_by VARCHAR(80), 
	created_at DATETIME(6), 
	PRIMARY KEY (id), 
	UNIQUE (certificate_no), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- owner
CREATE TABLE owner (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	unit_id INTEGER NOT NULL, 
	owner_name VARCHAR(200) NOT NULL, 
	contact_no VARCHAR(100), 
	email VARCHAR(200), 
	move_in DATE, 
	move_out DATE, 
	notes TEXT, 
	status VARCHAR(20), 
	receive_soa_email BOOL, 
	include_in_soa BOOL, 
	created_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- receipt
CREATE TABLE receipt (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	receipt_year INTEGER NOT NULL, 
	receipt_seq INTEGER NOT NULL, 
	receipt_no VARCHAR(20) NOT NULL, 
	unit_id INTEGER NOT NULL, 
	received_date DATE NOT NULL, 
	amount NUMERIC(12, 2) NOT NULL, 
	payment_method VARCHAR(20) NOT NULL, 
	reference VARCHAR(100), 
	remarks VARCHAR(300), 
	received_by VARCHAR(80), 
	source VARCHAR(20) NOT NULL, 
	voided_at DATETIME(6), 
	voided_by VARCHAR(80), 
	void_reason VARCHAR(500), 
	created_at DATETIME(6), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_receipt_year_seq UNIQUE (receipt_year, receipt_seq), 
	CONSTRAINT ck_receipt_amount_positive CHECK (amount > 0), 
	UNIQUE (receipt_no), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_receipt_unit_id ON receipt (unit_id);

-- resident_profile
CREATE TABLE resident_profile (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER NOT NULL, 
	unit_id INTEGER NOT NULL, 
	person_type VARCHAR(20), 
	person_id INTEGER, 
	display_name VARCHAR(200) NOT NULL, 
	active BOOL, 
	created_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES user (id), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- resident_unit_link
CREATE TABLE resident_unit_link (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	user_id INTEGER NOT NULL, 
	unit_id INTEGER NOT NULL, 
	person_type VARCHAR(20) NOT NULL, 
	person_id INTEGER, 
	active BOOL NOT NULL DEFAULT '1', 
	active_key VARCHAR(40), 
	created_at DATETIME(6), 
	created_by VARCHAR(80), 
	ended_at DATETIME(6), 
	ended_by VARCHAR(80), 
	end_reason VARCHAR(300), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_resident_unit_link_active_key UNIQUE (active_key), 
	FOREIGN KEY(user_id) REFERENCES user (id), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_resident_unit_link_unit ON resident_unit_link (unit_id);
CREATE INDEX ix_resident_unit_link_user ON resident_unit_link (user_id);

-- tenant
CREATE TABLE tenant (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	unit_id INTEGER NOT NULL, 
	tenant_name VARCHAR(200) NOT NULL, 
	contact_no VARCHAR(80), 
	email VARCHAR(160), 
	move_in DATE, 
	move_out DATE, 
	notes VARCHAR(500), 
	status VARCHAR(30), 
	representative BOOL, 
	receive_soa_email BOOL, 
	include_in_soa BOOL, 
	created_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- water_reading
CREATE TABLE water_reading (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	unit_id INTEGER NOT NULL, 
	reading_month VARCHAR(7) NOT NULL, 
	previous_reading DOUBLE, 
	current_reading DOUBLE, 
	rate DOUBLE, 
	reading_date DATE, 
	paid BOOL, 
	paid_amount NUMERIC(12, 2), 
	payment_method VARCHAR(20), 
	payment_type VARCHAR(20), 
	payment_reference VARCHAR(100), 
	paid_date DATE, 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_water_unit_month UNIQUE (unit_id, reading_month), 
	CONSTRAINT ck_water_month_format CHECK (reading_month LIKE '____-__' AND SUBSTR(reading_month, 1, 4) BETWEEN '1900' AND '2999' AND SUBSTR(reading_month, 6, 2) BETWEEN '01' AND '12'), 
	FOREIGN KEY(unit_id) REFERENCES unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_water_month ON water_reading (reading_month);
CREATE INDEX ix_water_unit_month ON water_reading (unit_id, reading_month);

-- advance_application
CREATE TABLE advance_application (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	advance_payment_id INTEGER NOT NULL, 
	billing_id INTEGER NOT NULL, 
	billing_month VARCHAR(7) NOT NULL, 
	amount NUMERIC(12, 2), 
	applied_date DATE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_advance_application_advance_billing UNIQUE (advance_payment_id, billing_id), 
	CONSTRAINT ck_advance_application_month_format CHECK (billing_month LIKE '____-__' AND SUBSTR(billing_month, 1, 4) BETWEEN '1900' AND '2999' AND SUBSTR(billing_month, 6, 2) BETWEEN '01' AND '12'), 
	CONSTRAINT ck_advance_application_amount_nonneg CHECK (amount >= 0), 
	FOREIGN KEY(advance_payment_id) REFERENCES advance_payment (id), 
	FOREIGN KEY(billing_id) REFERENCES billing (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_advance_application_advance ON advance_application (advance_payment_id);
CREATE INDEX ix_advance_application_billing ON advance_application (billing_id);

-- employee_payroll_statutory
CREATE TABLE employee_payroll_statutory (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	payroll_id INTEGER NOT NULL, 
	sss_employee NUMERIC(12, 2), 
	sss_employer NUMERIC(12, 2), 
	sss_ec_employer NUMERIC(12, 2), 
	philhealth_employee NUMERIC(12, 2), 
	philhealth_employer NUMERIC(12, 2), 
	pagibig_employee NUMERIC(12, 2), 
	pagibig_employer NUMERIC(12, 2), 
	withholding_tax NUMERIC(12, 2), 
	thirteenth_month NUMERIC(12, 2), 
	gross_pay NUMERIC(12, 2), 
	total_employee_deductions NUMERIC(12, 2), 
	total_employer_cost NUMERIC(12, 2), 
	net_pay_after_statutory NUMERIC(12, 2), 
	PRIMARY KEY (id), 
	FOREIGN KEY(payroll_id) REFERENCES employee_payroll (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE UNIQUE INDEX ix_employee_payroll_statutory_payroll_id ON employee_payroll_statutory (payroll_id);

-- import_crosswalk
CREATE TABLE import_crosswalk (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	source_id INTEGER NOT NULL, 
	entity_type VARCHAR(30) NOT NULL, 
	external_id VARCHAR(100) NOT NULL, 
	target_id INTEGER NOT NULL, 
	first_batch_id INTEGER, 
	last_batch_id INTEGER, 
	source_sheet VARCHAR(60), 
	source_row INTEGER, 
	created_at DATETIME(6), 
	updated_at DATETIME(6), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_import_crosswalk_external UNIQUE (source_id, entity_type, external_id), 
	CONSTRAINT uq_import_crosswalk_target UNIQUE (source_id, entity_type, target_id), 
	FOREIGN KEY(source_id) REFERENCES import_source (id), 
	FOREIGN KEY(first_batch_id) REFERENCES import_batch (id), 
	FOREIGN KEY(last_batch_id) REFERENCES import_batch (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_import_crosswalk_target ON import_crosswalk (entity_type, target_id);

-- maintenance_ticket
CREATE TABLE maintenance_ticket (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	ticket_no VARCHAR(40) NOT NULL, 
	unit_id INTEGER, 
	resident_profile_id INTEGER, 
	vendor_id INTEGER, 
	category VARCHAR(100), 
	title VARCHAR(200) NOT NULL, 
	description TEXT NOT NULL, 
	priority VARCHAR(20), 
	status VARCHAR(30), 
	assigned_to VARCHAR(120), 
	resolution TEXT, 
	requested_at DATETIME(6), 
	updated_at DATETIME(6), 
	PRIMARY KEY (id), 
	UNIQUE (ticket_no), 
	FOREIGN KEY(unit_id) REFERENCES unit (id), 
	FOREIGN KEY(resident_profile_id) REFERENCES resident_profile (id), 
	FOREIGN KEY(vendor_id) REFERENCES vendor (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- payment
CREATE TABLE payment (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	billing_id INTEGER NOT NULL, 
	amount NUMERIC(12, 2), 
	payment_date DATE, 
	payment_method VARCHAR(20), 
	payment_type VARCHAR(20), 
	reference VARCHAR(100), 
	remarks VARCHAR(300), 
	reversed_at DATETIME(6), 
	updated_at DATETIME(6), 
	updated_by VARCHAR(80), 
	PRIMARY KEY (id), 
	CONSTRAINT ck_payment_amount_nonneg CHECK (amount >= 0), 
	FOREIGN KEY(billing_id) REFERENCES billing (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_payment_billing ON payment (billing_id);

-- receipt_allocation
CREATE TABLE receipt_allocation (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	receipt_id INTEGER NOT NULL, 
	kind VARCHAR(10) NOT NULL, 
	payment_id INTEGER, 
	water_reading_id INTEGER, 
	advance_payment_id INTEGER, 
	amount NUMERIC(12, 2) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_receipt_allocation_kind CHECK (kind IN ('bill', 'water', 'advance')), 
	CONSTRAINT ck_receipt_allocation_amount_positive CHECK (amount > 0), 
	CONSTRAINT ck_receipt_allocation_target CHECK ((kind = 'bill' AND payment_id IS NOT NULL) OR (kind = 'water' AND water_reading_id IS NOT NULL) OR (kind = 'advance' AND advance_payment_id IS NOT NULL)), 
	FOREIGN KEY(receipt_id) REFERENCES receipt (id), 
	FOREIGN KEY(payment_id) REFERENCES payment (id), 
	FOREIGN KEY(water_reading_id) REFERENCES water_reading (id), 
	FOREIGN KEY(advance_payment_id) REFERENCES advance_payment (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX ix_receipt_allocation_advance_payment_id ON receipt_allocation (advance_payment_id);
CREATE INDEX ix_receipt_allocation_payment_id ON receipt_allocation (payment_id);
CREATE INDEX ix_receipt_allocation_receipt_id ON receipt_allocation (receipt_id);
CREATE INDEX ix_receipt_allocation_water_reading_id ON receipt_allocation (water_reading_id);

-- Indexes created at runtime by init_db() (not declared on the models)
CREATE INDEX `ix_owner_unit_id` ON `owner` (`unit_id`);
CREATE INDEX `ix_tenant_unit_id` ON `tenant` (`unit_id`);
CREATE INDEX `ix_tenant_status` ON `tenant` (`status`);
CREATE INDEX `ix_audit_log_created_at` ON `audit_log` (`created_at`);
