"""Generate database/schema.sql for a LOCAL MySQL 8 / MariaDB 10.4+ server.

The schema is derived from the SQLAlchemy models in backend/legacy_app.py, so it
matches exactly what the working system uses today. It is never edited by hand:

    python database/tools/generate_schema.py            write database/schema.sql
    python database/tools/generate_schema.py --check    exit 1 if schema.sql is stale

Safety: the models are imported against an in-memory SQLite database, so this
script never opens, creates or modifies cityland_condo_web.db or any MySQL server.

Type decisions (see docs/migration.md, section 4):
  * db.Float    -> DOUBLE       (MySQL FLOAT is single precision; SQLite REAL is double)
  * db.DateTime -> DATETIME(6)  (keeps the microseconds SQLite currently stores)
  * db.Numeric  -> DECIMAL(p,s) (unchanged)
  * every table -> InnoDB, utf8mb4, utf8mb4_bin (case/accent-sensitive like SQLite)
"""
import argparse
import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCHEMA_PATH = os.path.join(ROOT, "database", "schema.sql")

# Must be set before legacy_app is imported: it reads DATABASE_URL at import time.
os.environ["DATABASE_URL"] = "sqlite://"
sys.path.insert(0, os.path.join(ROOT, "backend"))
warnings.filterwarnings("ignore")

from sqlalchemy import DateTime, Float  # noqa: E402
from sqlalchemy.dialects import mysql  # noqa: E402
from sqlalchemy.ext.compiler import compiles  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

TABLE_OPTIONS = {"mysql_engine": "InnoDB", "mysql_charset": "utf8mb4", "mysql_collate": "utf8mb4_bin"}

# Indexes that init_db() creates with raw SQL instead of declaring them on the models.
RUNTIME_INDEXES = [
    ("ix_owner_unit_id", "owner", "unit_id"),
    ("ix_tenant_unit_id", "tenant", "unit_id"),
    ("ix_tenant_status", "tenant", "status"),
    ("ix_audit_log_created_at", "audit_log", "created_at"),
]


@compiles(Float, "mysql")
def _float_as_double(type_, compiler, **kw):
    return "DOUBLE"


@compiles(DateTime, "mysql")
def _datetime_with_microseconds(type_, compiler, **kw):
    return "DATETIME(6)"


def build_schema():
    import legacy_app

    metadata = legacy_app.db.metadata
    dialect = mysql.dialect()
    out = [
        "-- CityLand 9 Condo Management System: local MySQL 8 / MariaDB 10.4+ schema",
        "-- GENERATED by database/tools/generate_schema.py from backend/legacy_app.py.",
        "-- Do not edit by hand; change the models and regenerate.",
        "--",
        "-- Apply ONLY to a new, empty database, for example:",
        "--   CREATE DATABASE cityland9 CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;",
        "--   mysql -u <user> -p cityland9 < database/schema.sql",
        "--",
        f"-- Tables: {len(metadata.sorted_tables)} (ordered so foreign-key targets are created first)",
        "",
        "SET NAMES utf8mb4;",
        "",
    ]
    for table in metadata.sorted_tables:
        for key, value in TABLE_OPTIONS.items():
            table.dialect_kwargs[key] = value
        out.append(f"-- {table.name}")
        out.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name):
            out.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        out.append("")

    out.append("-- Indexes created at runtime by init_db() (not declared on the models)")
    for name, table, column in RUNTIME_INDEXES:
        out.append(f"CREATE INDEX `{name}` ON `{table}` (`{column}`);")
    out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if database/schema.sql is out of date")
    args = parser.parse_args()

    schema = build_schema()
    if args.check:
        current = open(SCHEMA_PATH, encoding="utf-8").read() if os.path.exists(SCHEMA_PATH) else ""
        if current != schema:
            print("database/schema.sql is out of date. Run: python database/tools/generate_schema.py")
            return 1
        print("database/schema.sql is up to date.")
        return 0

    with open(SCHEMA_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(schema)
    print(f"Wrote {SCHEMA_PATH} ({schema.count('CREATE TABLE')} tables, {schema.count('CREATE INDEX') + schema.count('CREATE UNIQUE INDEX')} indexes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
